[package]
name = "timer"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
oak = { path = "../../", features = ["use-time"] }
wasm-bindgen = { version = "0.2" }