[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "crates/oak",
    "crates/oak_app",
    "crates/oak_dom_browser",
    "crates/oak_dom_diff",
    "crates/oak_dom_node",
    # "crates/oak_macros",
    # "crates/oak_macros_impl",
    # "crates/syn_markup",
    "examples/counter",
    "examples/hello",
]
