[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "crates/oak",
    "crates/oak_app",
    "crates/oak_core",
    "crates/oak_dom",
    "crates/oak_events",
    "examples/counter",
]
