[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "crates/oak",
    "crates/oak_browser",
    "crates/oak_core",
    "crates/oak_diff",
    "crates/oak_html",
    "crates/oak_http",
    "crates/oak_time",
    "crates/oak_vdom",
    "examples/counter",
    "examples/hello",
    # "examples/timer",
]
