[package]
name = "oak_macros"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
proc-macro-nested = "0.1"
oak_macros_impl = { path = "../oak_macros_impl" }

[dev-dependencies]
oak_dom_node = { path = "../oak_dom_node" }