[package]
name = "oak"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
itertools = "0.7.8"
log = "0.4"
wasm-bindgen = { version="0.2", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-logger = { version = "0.1", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }

[dependencies.web-sys]
version="0.3"
optional = true
features = [
  'console',
  'Document',
  'DocumentFragment',
  'Text',
  'Element',
  'HtmlElement',
  'HtmlInputElement',
  'Node',
  'NodeList',
  'Window',
  'EventListener',
  'EventTarget',
  'Event',
  'KeyboardEvent',
  'MouseEvent',
  'CssStyleDeclaration',
  'Performance'
]

[features]
default = ["browser"]
js = ["js-sys", "wasm-logger", "wasm-bindgen", "console_error_panic_hook"]
browser = ["js", "web-sys"]
nightly = ["wasm-bindgen/nightly"]