[package]
name = "oak"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.4"
itertools = "0.7.8"
lazy_static = "1.1.0"

[dependencies.web-sys]
version="0.3.2"
features = [
  'console',
  'Document',
  'DocumentFragment',
  'Text',
  'Element',
  'HtmlElement',
  'HtmlInputElement',
  'Node',
  'NodeList',
  'Window',
  'EventListener',
  'EventTarget',
  'Event',
  'KeyboardEvent',
  'MouseEvent',
  'CssStyleDeclaration',
  'Performance'
]

[dev-dependencies]
wasm-bindgen-test = "0.2"