[package]
name = "uibench"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
oak = { path = "../../crates/oak" }
wasm-bindgen = "0.2"
js-sys = "0.3"