[package]
name = "time"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oak = {path="../../crates/oak"}
wasm-bindgen = { version="0.2" }