[package]
name = "oak_core"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
wasm-bindgen-futures = "0.3"
wasm-bindgen = "0.2"
futures = "0.1"
js-sys = "0.3"
log = "0.4"